const types = {
  SET_CUSTOMER: '@shop/SET_CUSTOMER',
  REQUEST_PRODUCERS: '@shop/REQUEST_PRODUCERS',
  SET_PRODUCERS: '@shop/SET_PRODUCERS',
  SET_SELECTED_PRODUCER_MAP_MARKER: '@shop/SET_SELECTED_PRODUCER_MAP_MARKER',
  SET_MAP_CENTER: '@shop/SET_MAP_CENTER',
  REQUEST_PRODUCER: '@shop/REQUEST_PRODUCER',
  SET_PRODUCER: '@shop/SET_PRODUCER',
  HANDLE_PRODUCT_CART: '@shop/HANDLE_PRODUCT_CART',
  REQUEST_LOGIN: '@shop/REQUEST_LOGIN',
  SET_LOGIN: '@shop/SET_LOGIN',
  POST_PRODUCT: '@shop/POST_PRODUCT',
  DELETE_PRODUCT: '@shop/DELETE_PRODUCT',
  POST_PRODUCER: '@shop/POST_PRODUCER',
  PATCH_PRODUCER_ADDRESS: '@shop/PATCH_PRODUCER_ADDRESS',
  PATCH_PRODUCER_DATA: '@shop/PATCH_PRODUCER_DATA',
};

export default types;
