const types = {
  SET_CUSTOMER: '@shop/SET_CUSTOMER',
  REQUEST_PRODUCERS: '@shop/REQUEST_PRODUCERS',
  SET_PRODUCERS: '@shop/SET_PRODUCERS',
  SET_SELECTED_PRODUCER_MAP_MARKER: '@shop/SET_SELECTED_PRODUCER_MAP_MARKER',
  SET_MAP_CENTER: '@shop/SET_MAP_CENTER',
  REQUEST_PRODUCER: '@shop/REQUEST_PRODUCER',
  SET_PRODUCER: '@shop/SET_PRODUCER',
};

export default types;
